spring.application.name=carrental-server
spring.datasource.url=jdbc:mysql://localhost:3306/car_rental?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC&createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=codegym123456789
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect
server.port=8080
jwt.secret=sTxRGCzqmhLM7jKZjCK8RP+PpBhCT7jY3aKXk5ocb2nPzD+cL5RfQ3DwEVYiZwQ+nDnLZ0kXt68UXMNokiyh1g==
jwt.expiration=86400000
